package entities.enuns;

public enum Categoria {
	
	FICÇÃO, ROMANCE, TERROR, SUSPENSE, MISTÉRIO, FANTASIA, AVENTURA, 
	FICÇÃO_CIENTÍFICA, BIOGRAFIA, AUTOBIOGRAFIA, HISTÓRIA, RELIGIÃO, AUTOAJUDA, FILOSOFIA, 
	PSICOLOGIA, EDUCAÇÃO, NEGÓCIOS, ECONOMIA, POLÍTICA, DIREITO, ARTE, MÚSICA, POESIA, DRAMA, 
	HUMOR, ENSAIO, VIAGEM, GASTRONOMIA, SAÚDE, ESPIRITUALIDADE, TECNOLOGIA, INFORMÁTICA, CIÊNCIA, 
	INFANTOJUVENIL, DIDÁTICO, CLÁSSICOS, QUADRINHOS, MANGÁ, MANUAL, GUIA, MITOLOGIA
	
}
